[project]
name = "lecture-extractor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "questionary>=2.1.1",
    "requests>=2.32.5",
    "rich>=14.2.0",
]
